#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# This wizard writes no GitHub secrets and no .env: `grep -rn "secrets\.\|vars\."
# .github/` returns nothing, so CI needs no credentials from you. What it does
# capture is verification evidence, which lands in .scratch/ci-evidence.env so
# the next agent turn can read it instead of asking you again.
cd "$(dirname "${BASH_SOURCE[0]}")/.."
ENV_FILE=".scratch/ci-evidence.env"

REPO="Catzpro01/n8n-rust-v3.0"
PR=16
KEEP_VALIDATE_RUN=34887094932   # Validate, pull_request, head 8ded14e
KEEP_ECO_RUN=34887094917        # Eco 100K Summarize acceptance, head 8ded14e
KEEP_IF_RUN=34887094941         # If runtime acceptance, head 8ded14e

# Queued runs whose content is superseded: six from the already-merged branch
# arena/01a0a0c6-n8n-rust-v3-0, and five from this branch's superseded commit
# ec07446. Cancelling them is what frees the single self-hosted runner.
STALE_RUNS=(
  34884406719 34881819585 34882805776 34882805777 34884406664 34884406697
  34886806779 34886806798 34886806807 34886850087 34886850093
)
# Trunk runs for the merge commit. PR #16 supersedes this tree, but cancelling
# trunk evidence is a judgement call, so it is asked about separately.
MAIN_RUNS=(34884429635 34884429694)

banner "Unblock CI evidence for PR #${PR}"

# ── Stage 1 ──────────────────────────────────────────────────────────────
stage "Self-hosted runner: is it alive?"
say "16 workflow runs are queued and none is in progress, which means the"
say "runner stopped picking up jobs rather than running slowly."
open_url "https://github.com/${REPO}/settings/actions/runners"
step "Read the runner's status: Idle (free), Active (busy), or Offline."
warn "If it is Offline, the VPS runner service is down. On the VPS run:"
note "    systemctl list-units --all --type=service | grep -i 'actions\\.runner'"
note "    sudo systemctl restart <that-unit>"
note "  or, from the runner directory: sudo ./svc.sh status && sudo ./svc.sh start"
note "  Worth checking while you are there: free -m and df -h ."
ask RUNNER_STATE "Runner status you saw (idle/active/offline-restarted):"
write_env RUNNER_STATE "$RUNNER_STATE"

# ── Stage 2 ──────────────────────────────────────────────────────────────
stage "Optional: let agents cancel runs"
say "The agent's GitHub token is refused when it cancels a run:"
note "    HTTP 403: Resource not accessible by integration"
say "That is a missing 'Actions: write' permission on the app installation."
say "Granting it means the next session can trim the queue itself. Skip freely."
open_url "https://github.com/settings/installations"
step "Find the Arena app → Configure → this repository → Repository permissions."
step "Set Actions to 'Read and write', then Save."
if confirm "Did you grant Actions: write?"; then
  write_env APP_ACTIONS_WRITE "granted"
else
  write_env APP_ACTIONS_WRITE "not-granted"
  note "Fine — you will do the cancelling yourself in the next stage."
fi

# ── Stage 3 ──────────────────────────────────────────────────────────────
stage "Cancel the superseded queued runs"
say "These 11 runs test content that PR #${PR} replaces. Cancelling them is"
say "what lets the runner reach the run we actually need."
for id in "${STALE_RUNS[@]}"; do note "    $id"; done
note "  Re-derive the list any time with:"
note "    gh run list --repo ${REPO} --limit 40"
if confirm "Cancel those ${#STALE_RUNS[@]} superseded runs now?"; then
  cancelled=0
  for id in "${STALE_RUNS[@]}"; do
    if gh run cancel "$id" --repo "$REPO" >/dev/null 2>&1; then
      cancelled=$((cancelled + 1)); printf '  %s✓%s cancelled %s\n' "$GREEN" "$RESET" "$id"
    else
      warn "could not cancel $id (already finished, or your token lacks rights)"
    fi
  done
  write_env STALE_RUNS_CANCELLED "$cancelled"
else
  write_env STALE_RUNS_CANCELLED "0"
fi
say ""
say "Separately, these two are the trunk runs for the merge commit 24bc367:"
for id in "${MAIN_RUNS[@]}"; do note "    $id"; done
if confirm "Cancel the trunk runs too? (default no)"; then
  for id in "${MAIN_RUNS[@]}"; do gh run cancel "$id" --repo "$REPO" || warn "could not cancel $id"; done
  write_env MAIN_RUNS_CANCELLED "yes"
else
  write_env MAIN_RUNS_CANCELLED "no"
fi

# ── Stage 4 ──────────────────────────────────────────────────────────────
stage "Watch the Validate run reach the artifact step"
say "This is the step that has never passed: 'Browser acceptance: artifact"
say "generation'. Everything else in that workflow already passes."
open_url "https://github.com/${REPO}/actions/runs/${KEEP_VALIDATE_RUN}"
note "  Or follow it in the terminal:  gh run watch ${KEEP_VALIDATE_RUN} --repo ${REPO}"
note "  Then read one step's verdict:"
note "    gh run view ${KEEP_VALIDATE_RUN} --repo ${REPO} \\"
note "      --json jobs --jq '.jobs[]|select(.name==\"validate\")|.steps[]|select(.name|test(\"artifact generation\"))|.conclusion'"
step "Wait for that step to finish, then tell me what it says."
ask ARTIFACT_STEP_RESULT "Conclusion (success / failure / cancelled / still-running):"
write_env ARTIFACT_STEP_RESULT "$ARTIFACT_STEP_RESULT"
write_env VALIDATE_RUN_ID "$KEEP_VALIDATE_RUN"

# ── Stage 5 ──────────────────────────────────────────────────────────────
stage "If it failed: mismatch or regression?"
say "A readable failure here is progress, not defeat. The old code was"
say "OOM-killed; a message with byte counts and a sha256 means the rendered"
say "PNG genuinely differs from the committed baseline on this host."
open_url "https://github.com/${REPO}/actions/runs/${KEEP_VALIDATE_RUN}"
step "On the failed run, download the artifact named"
note "    visual-baseline-actual-<sha>"
step "Compare it with the committed baseline of the same name:"
note "    editor/tests/baselines/generate-progress.desktop.png"
note "    editor/tests/baselines/generate-progress.mobile.png"
say "Decide: a font/rendering difference on the runner means approve the new"
say "baseline with UPDATE_VISUAL_BASELINE=1 in its own commit. A layout or"
say "content difference means the UI regressed and the baseline stays."
ask BASELINE_DECISION "Decision (approve-baseline / real-regression / not-applicable):"
write_env BASELINE_DECISION "$BASELINE_DECISION"

# ── Stage 6 ──────────────────────────────────────────────────────────────
stage "Hand the evidence back"
say "Paste the block below into the agent chat. It is what lets the next turn"
say "record pinned evidence and promote Ticket 11 without re-asking you."
printf '\n'
note "---- paste from here ----"
printf '  runner=%s app_actions_write=%s cancelled=%s\n' \
  "${RUNNER_STATE:-unknown}" "${APP_ACTIONS_WRITE:-unknown}" "${STALE_RUNS_CANCELLED:-0}"
printf '  validate_run=%s artifact_generation_step=%s baseline_decision=%s\n' \
  "${VALIDATE_RUN_ID:-$KEEP_VALIDATE_RUN}" "${ARTIFACT_STEP_RESULT:-unknown}" "${BASELINE_DECISION:-unknown}"
printf '  if_run=%s eco_run=%s\n' "$KEEP_IF_RUN" "$KEEP_ECO_RUN"
note "---- paste to here ----"
printf '\n'
pause "Done?"

finish
