#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
set -euo pipefail

bundle="out/tracer-bundle"
bind="127.0.0.1:8787"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --bundle) bundle=${2:?missing bundle path}; shift 2 ;;
    --bind) bind=${2:?missing bind address}; shift 2 ;;
    *) echo "unknown install option: $1" >&2; exit 2 ;;
  esac
done

if [[ ${EUID} -ne 0 ]]; then
  echo "install.sh must run as root" >&2
  exit 1
fi
bundle=$(realpath "$bundle")
for required in \
  checksums.sha256 \
  usr/bin/workflowd \
  usr/lib/systemd/system/workflowd.service \
  release/release-manifest.json; do
  [[ -f "$bundle/$required" ]] || { echo "bundle missing $required" >&2; exit 1; }
done
(cd "$bundle" && sha256sum --check --strict --quiet checksums.sha256)

if ! getent group workflowd >/dev/null; then
  groupadd --system workflowd
fi
if ! id workflowd >/dev/null 2>&1; then
  useradd --system --gid workflowd --home-dir /var/lib/workflow-rust \
    --shell /usr/sbin/nologin --no-create-home workflowd
fi

install -D -o root -g root -m 0755 "$bundle/usr/bin/workflowd" /usr/bin/workflowd
install -D -o root -g root -m 0644 \
  "$bundle/usr/lib/systemd/system/workflowd.service" \
  /etc/systemd/system/workflowd.service
install -d -o root -g workflowd -m 0750 /etc/workflowd
if [[ ! -f /etc/workflowd/master.key ]]; then
  umask 077
  head -c 32 /dev/urandom > /etc/workflowd/master.key
fi
chown root:root /etc/workflowd/master.key
chmod 0600 /etc/workflowd/master.key
cat > /etc/workflowd/workflowd.env <<ENV
# Generated by the Canopy Workbench installer.
WORKFLOWD_BIND=$bind
WORKFLOWD_STATE_DIR=/var/lib/workflow-rust
ENV
chown root:workflowd /etc/workflowd/workflowd.env
chmod 0640 /etc/workflowd/workflowd.env
install -d -o root -g root -m 0755 /usr/share/doc/workflowd
cp -a "$bundle/usr/share/doc/workflowd/." /usr/share/doc/workflowd/
chown -R root:root /usr/share/doc/workflowd
find /usr/share/doc/workflowd -type d -exec chmod 0755 {} +
find /usr/share/doc/workflowd -type f -exec chmod 0644 {} +

systemctl daemon-reload
systemctl enable --now workflowd.service
for _ in {1..100}; do
  if systemctl is-active --quiet workflowd.service; then
    exit 0
  fi
  sleep 0.1
done
systemctl status --no-pager workflowd.service >&2 || true
exit 1
